namespace: ${DT_APP_NAMESPACE}

image:
  repository: ${DT_REGISTRY_NAME}:${DT_REGISTRY_HOST_PORT}/postgres:17.5-alpine3.21
  pullPolicy: IfNotPresent

database:
  name: ${DT_POSTGRES_DB_NAME}
  user: ${DT_POSTGRES_DB_ADMIN_USERNAME}
  password: ${DT_POSTGRES_DB_ADMIN_PASSWORD}

service:
  type: ${DT_POSTGRES_SERVICE_TYPE}
  port: ${DT_POSTGRES_CONTAINER_PORT}
  nodePort: ${DT_POSTGRES_NODE_PORT}

persistence:
  size: 3Gi